version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
     - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root Agora nas novas versões da imagem do MySQL 5.7,
      #  a variável MYSQL_USER=root não é aceita, 
      #  porque o usuário root do banco já é criado por padrão,
      #  então lançará um erro dizendo que está se tentando criar um usuário que já existe.
      #  De qualquer forma, mesmo na versões antigas, se quisermos trabalhar com usuário root do banco,
      #  esta variável não precisa ser passada.
    networks: 
      - node-network



networks: 
  node-network:
    driver: bridge